on:
  push:
    branches: [ main ]
  pull_request:

name: Continuous integration

jobs:

  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_name: [windows, ubuntu, macos-x86, macos-aarch64]
        include:
          - build_name: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build_name: ubuntu
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build_name: macos-x86
            os: macos-latest
            target: x86_64-apple-darwin
          - build_name: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Update Rust
        run: |
          rustup update
          rustup target add ${{ matrix.target }}

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Build
        run: cargo check --verbose --locked --target ${{ matrix.target }}

  check-publish:
    name: Check cargo publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Update Rust
        run: rustup update

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Publish Dry-run
        run: cargo publish --dry-run --verbose --locked

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Update Rust
        run: rustup update

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Unit Tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Update Rust
        run: rustup update

      - name: Add rustfmt
        run: rustup component add rustfmt

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Update Rust
        run: rustup update

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Add Clippy
        run: rustup component add clippy

      - name: Lint
        run: cargo clippy -- -D warnings
